namespace Jarvis.Runtime;

public enum CapabilityStatus { Working, Partial, Foundation, Planned }

public sealed record Capability(string Area, string Name, CapabilityStatus Status, string Notes, int Phase);

/// <summary>
/// An honest map of what JARVIS can and cannot do in this build, shown in the dashboard.
/// "Working" means real and tested; "Partial" works with stated limits; "Foundation" means the
/// architecture exists but the user-facing feature isn't there yet; "Planned" is not started.
/// </summary>
public static class Capabilities
{
    public static IReadOnlyList<Capability> All(bool windows) =>
    [
        new("Core", "Always-on runtime, local API, event stream", CapabilityStatus.Working, "jarvis-core runs in the background; the UI can close without stopping it.", 1),
        new("Core", "Start with Windows", windows ? CapabilityStatus.Working : CapabilityStatus.Planned, "Per-user Run key, toggled in Settings.", 1),
        new("Core", "Agent loop with tools and approvals", CapabilityStatus.Working, "Deterministic commands, AI planning with tool calls, permission checks, audit log.", 1),
        new("Language", "English and Egyptian Arabic", CapabilityStatus.Working, "Auto-detection, bilingual commands and replies; AI replies in Egyptian Arabic when you speak Arabic.", 1),
        new("AI", "Local AI (Ollama / LM Studio / llama.cpp)", CapabilityStatus.Working, "Native Ollama API: model discovery with real capabilities (tools/vision/embeddings), context sizing, streaming, downloads from Settings. Any OpenAI-compatible server also works. Verified in CI against a real Ollama model.", 1),
        new("AI", "Fallback, streaming, context management", CapabilityStatus.Working, "A failing model hands over to the next one; replies stream as they're written; long conversations are condensed to fit small local models; models without tool support still converse.", 1),
        new("AI", "Optional cloud AI (Anthropic, Google Gemini, OpenAI-compatible)", CapabilityStatus.Working, "Off by default. Needs your own API key and 'Allow cloud AI'. Gemini uses Google's OpenAI-compatible endpoint with a key from aistudio.google.com; chat confirmed with Google's servers by the user; tool calls send back Gemini's thought signatures (tested against a stand-in that enforces Google's rule).", 1),
        new("AI", "Router (no-AI / local / cloud by task)", CapabilityStatus.Partial, "Keyword task classes plus capability-aware model choice (prefers tool-capable ~7-8B models). No cost/latency model yet. Deterministic commands never use AI.", 1),
        new("Voice", "Push-to-talk with local Whisper", windows ? CapabilityStatus.Partial : CapabilityStatus.Foundation, "Requires downloading a speech model in Settings → Voice. Verified end to end on Windows in CI (speech → Whisper → command). Arabic accuracy depends on model size.", 1),
        new("Voice", "Wake word \"Jarvis\"", windows ? CapabilityStatus.Partial : CapabilityStatus.Foundation, "Off by default. Uses speech detection + Whisper keyword spotting; a dedicated low-power wake-word model is planned.", 1),
        new("Voice", "Spoken replies (Windows voices)", windows ? CapabilityStatus.Working : CapabilityStatus.Foundation, "Arabic speech needs an Arabic Windows voice installed.", 1),
        new("Computer", "Open/close apps, windows, processes", windows ? CapabilityStatus.Working : CapabilityStatus.Planned, "Start-menu apps (classic + Store), settings pages, folders, websites. English/Arabic names.", 2),
        new("Computer", "Volume, media keys, lock, power, screenshots", windows ? CapabilityStatus.Working : CapabilityStatus.Planned, "Shutdown/restart always need approval and wait 30 seconds.", 2),
        new("Computer", "Keyboard input and shortcuts, clipboard", windows ? CapabilityStatus.Working : CapabilityStatus.Planned, "Need approval because keystrokes go to the focused app.", 2),
        new("Computer", "Run PowerShell/cmd commands", CapabilityStatus.Working, "Read-only commands run freely; others need approval; destructive ones are critical.", 2),
        new("Computer", "UI Automation: read and operate other apps' controls (buttons, fields, menus, tabs)", windows ? CapabilityStatus.Working : CapabilityStatus.Planned, "Windows UI Automation (the accessibility layer), real button presses and field values, verified read-back; consequential buttons and password fields always ask; mouse click/scroll as a fallback. Verified on Windows CI with Notepad.", 2),
        new("Developer", "Find, open and build code projects; extract build errors", CapabilityStatus.Working, "npm/pnpm/yarn, dotnet, cargo, go, python, gradle, maven, cmake, make. Builds need approval.", 2),
        new("Files", "Search, read, write, move, delete (Recycle Bin)", CapabilityStatus.Working, "Name search over your folders; protected locations require approval.", 2),
        new("Files", "Document knowledge: PDF, Word, Excel, PowerPoint, OpenDocument, RTF, text/code, ZIP listings, images (OCR)", CapabilityStatus.Working, "Opt-in local index of your chosen folders (Settings → Files), kept current as files change. Image text and scanned PDFs (first 20 pages) use Windows OCR on Windows.", 6),
        new("Files", "Search documents by words or meaning; latest files; key points; version comparison", CapabilityStatus.Working, "\"find documents about the renewal fee\", \"what's my latest PDF\", \"summarize X\", \"compare X with the previous version\". Meaning-based search needs a local embedding model (bge-m3). Key points are extracted sentences; AI summaries are written from the real text when a model is available.", 6),
        new("Files", "Documents linked to people and organisations", CapabilityStatus.Working, "Files mentioning a known person/organisation appear on their profile.", 6),
        new("Memory", "Local memory: add, search, edit, delete, clear", CapabilityStatus.Working, "SQLite full-text search with Arabic normalization; kinds, sources and provenance (why each item is stored).", 3),
        new("Memory", "Confirmed vs inferred, review and confirm/reject", CapabilityStatus.Working, "Inferences never become facts without you.", 3),
        new("Memory", "People, organisations, projects and relationships", CapabilityStatus.Working, "\"Ahmed works at CityCrep\"; profiles gather memories, relationships and related tasks.", 3),
        new("Memory", "Semantic (meaning-based) search", CapabilityStatus.Working, "Needs a free local embedding model (bge-m3 via Ollama, multilingual); keyword search otherwise. Verified in CI with real models: all-minilm (English) and bge-m3 (Arabic).", 3),
        new("Memory", "Conversation history", CapabilityStatus.Working, "Stored locally with a retention period.", 3),
        new("Tasks", "Tasks and reminders", CapabilityStatus.Working, "States: pending, in progress, waiting, blocked, completed, cancelled.", 5),
        new("Tasks", "Daily briefing and priorities", CapabilityStatus.Working, "\"What's happening today?\" / \"Check my priorities\" summarise real reminders, tasks, approvals and queued work. No AI needed.", 5),
        new("Interface", "HUD dashboard, command console, 8-state orb, system monitor", CapabilityStatus.Working, "Streaming replies with live progress; English and Arabic (RTL) interface; appearance, sounds and shortcuts are configurable.", 1),
        new("Tasks", "Workflows (\"track the CityCrep deal\")", CapabilityStatus.Working, "Steps with dependencies, deadlines, waiting-for + follow-up nudges, approval-gated business steps, recurring cycles, history.", 5),
        new("Tasks", "Recurring tasks", CapabilityStatus.Working, "\"every monday\", \"كل شهر\", working days (Sun–Thu)…", 5),
        new("Notifications", "Priority, dedupe, meeting/fullscreen-aware holding, digest", windows ? CapabilityStatus.Working : CapabilityStatus.Partial, "Windows toasts and spoken alerts.", 5),
        new("Presence", "Active app, idle, fullscreen, meeting detection", windows ? CapabilityStatus.Working : CapabilityStatus.Planned, "Meeting = a call app using the microphone. Presence never uses the camera.", 1),
        new("Web", "Web search and page reading", CapabilityStatus.Partial, "Key-less DuckDuckGo search can be rate-limited; page text extraction; untrusted-content handling.", 4),
        new("Web", "Browser agent: open pages, read them, click, fill forms, search, go back, screenshot", CapabilityStatus.Working, "Drives Microsoft Edge/Chrome (its own visible window and profile) over the DevTools protocol — no extra download. Sending, buying, publishing, deleting, booking and form submission always ask; nothing suggested after reading a page runs without your OK. Verified in CI with a real browser.", 4),
        new("Web", "File downloads and multi-tab research in the browser", CapabilityStatus.Planned, "Comparisons currently combine search, page reading and the browser one page at a time.", 4),
        new("Offline", "Offline detection and queued online actions", CapabilityStatus.Working, "Queued actions wait for your OK when the connection returns.", 1),
        new("Privacy", "Screen-capture switch", CapabilityStatus.Working, "Settings → Privacy can block every screen-capture tool.", 1),
        new("Security", "Encrypted secrets, PIN lock, permission levels, audit", CapabilityStatus.Working, windows ? "Secrets use Windows DPAPI." : "Secrets use an AES key file (dev builds).", 1),
        new("Inbox", "Executive inbox over IMAP/SMTP (Gmail with an app password, Yahoo, iCloud, Zoho, company servers)", CapabilityStatus.Working, "Read-only sync, sorting into urgent / needs reply / important / FYI / noise with the reason shown, links to people and organisations, urgent alerts, drafts. Sending is a critical action that always asks. Verified in CI against a real mail server.", 6),
        new("Inbox", "Outlook.com / Microsoft 365 and Google sign-in (OAuth)", CapabilityStatus.Planned, "Microsoft turned off password sign-in for Outlook mail; needs an app registration and sign-in flow.", 6),
        new("Inbox", "WhatsApp, Instagram, Facebook, LinkedIn, X messages", CapabilityStatus.Planned, "Shown honestly in Settings → Accounts: official business APIs only (WhatsApp/Instagram/Messenger), paid (X), or not possible (LinkedIn).", 6),
        new("Inbox", "AI-written replies in your style", CapabilityStatus.Partial, "With a model, JARVIS reads the email and saves a draft for you to edit. Your confirmed writing style (Settings → Memory) reaches the model as a preference; drafting is verified only with a test model so far.", 6),
        new("Calendar", "Calendars: subscribe to Google/Outlook/iCloud via their private iCal address, plus JARVIS's own calendar", CapabilityStatus.Working, "Read-only subscriptions (recurrences expanded, address stored encrypted); add events by voice/text (EN/AR dates and times); agenda and next-meeting questions; reminders before meetings; today's meetings in the briefing.", 7),
        new("Calendar", "Meeting preparation", CapabilityStatus.Working, "\"Prepare me for my CityCrep meeting\": attendees and what JARVIS knows about them, tracked deals, open tasks, recent email and documents — from real data; a model polishes it when available.", 7),
        new("Calendar", "Two-way calendar sync and sending invites", CapabilityStatus.Planned, "Needs Google/Microsoft sign-in (OAuth) or CalDAV; until then nothing is changed in your online calendar.", 7),
        new("Meetings", "Meeting recording, local transcript, decisions and action items", windows ? CapabilityStatus.Working : CapabilityStatus.Planned, "You start it (it always asks), it's visible everywhere (REC in the dashboard, red dot on the orb), it stops by itself after the time limit. Microphone + what you hear, transcribed with local Whisper; audio is never stored. Decisions, action items (owner and date) and open questions; chosen items become tasks. Transcription verified on Windows CI with spoken audio; live capture needs real audio devices.", 7),
        new("Vision", "Screen understanding (\"what's on my screen?\")", windows ? CapabilityStatus.Partial : CapabilityStatus.Planned, "A local vision model (e.g. qwen2.5vl) looks at a screenshot; without one, JARVIS reads the screen text with Windows OCR and says so. Respects Settings → Privacy → screen capture. The OCR path is verified on Windows; the vision-model step is verified in CI with qwen2.5vl on a test picture, not yet end to end on a real screen.", 7),
        new("Vision", "Camera: one photo when you ask (\"what am I holding?\")", windows ? CapabilityStatus.Partial : CapabilityStatus.Planned, "Off by default; asks every time; single photo kept in memory only; never video. Needs a camera and a vision model; not verifiable in CI (no camera).", 7),
        new("Adaptation", "Opt-in pattern learning (routines, language, brevity)", CapabilityStatus.Working, "Off by default; proposals carry their evidence and wait for your confirmation.", 8),
        new("Adaptation", "Remember things from conversations (opt-in)", CapabilityStatus.Working, "After a conversation goes quiet, lasting facts you stated are proposed for review — each backed by a quote of your own words, checked against the transcript. Needs an AI model.", 8),
        new("Adaptation", "Writing-style learning from email you sent", CapabilityStatus.Working, "Off by default (Settings → Memory). Reads your Sent folder read-only and drafts you approved; proposes how you write (greeting, sign-off, length, language) for drafts in your voice; you confirm or reject it. Turning it off deletes the samples.", 8),
        new("Learning", "Research topics and learn from pages/documents, with sources and conflict detection", CapabilityStatus.Working, "\"Research …\" / \"learn from <link or file>\": facts are saved as unconfirmed notes citing their source; contradictions with what JARVIS knows are flagged for you. Source text is treated as untrusted. \"Keep me updated on …\" re-researches a topic on a schedule and notifies you only when something is new. Needs an AI model.", 10),
        new("Plugins", "Sandboxed plugins: JARVIS writes them from a description or you import them", CapabilityStatus.Working, "JavaScript in a sandbox (Jint) with no access to files, apps or JARVIS's data; network only to hosts you approve; time, step, memory and recursion limits. Lifecycle: draft → validate → tests with the network off → you review permissions → explicit approval → install. Changed files after approval stop the plugin loading. Updates show what they'd change (new hosts, sending, tools, risk) and need the same approval. Writing a plugin needs an AI model.", 9),
        new("Devices", "Phone companion (any phone browser on your Wi-Fi)", CapabilityStatus.Working, "Off by default. Settings → Devices: a separate server with JARVIS's own certificate, one-time pairing codes (QR), revocable per-phone tokens. Today's briefing, approvals, alerts and chat; anything a phone asks for that changes something always needs confirmation. Verified end to end over pinned TLS in tests.", 11),
        new("Devices", "Android app (pinned pairing, notifications with Approve/Refuse)", CapabilityStatus.Partial, "Built and unit-tested in CI, including certificate pinning against a real HTTPS server (a server with another certificate is refused before the token is sent); the debug APK is attached to releases for sideloading. Not yet tried on a physical phone. Alerts arrive every ~15 minutes (Android's minimum); \"Stay connected\" (opt-in, permanent notification) checks every 15 seconds so approvals arrive before they expire. Works only on the same network as the PC — no cloud relay.", 11),
    ];
}
